 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ULTRASONIC driver
 *
 * Author: Youssef Ahmed
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ICU_CLOCK               F_CPU_8
#define ICU_EDGE_TYPE           RISING
#define TRIGGER_PORT_ID         PORTB_ID
#define TRIGGER_PIN_ID          PIN5_ID
/*definition of the calibration factor in (uSec/cm)*/
#define CALIBRATION_FACTOR		58

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/


/*
 * Description :
 * Initialize the ULTRASONIC:
 * 1. Initialize the ICU driver.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the ULTRASONIC.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU.
 * 3. Return the measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * 1. The call back function called by the ICU driver.
 * 2. calculate the high time (pulse time) generated by the ULTRASONIC sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
