 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ULTRASONIC driver
 *
 * Author: Youssef Ahmed
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>
#include <math.h> /* to use round function */

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ULTRASONIC:
 * 1. Initialize the ICU driver.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin.
 */
void Ultrasonic_init(void)
{
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {ICU_CLOCK,ICU_EDGE_TYPE};
	/* Initialize the ICU driver */
	Icu_init(&Icu_Config);
	/* Setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);
}

/*
 * Description :
 * Send the Trigger pulse to the ULTRASONIC.
 */
void Ultrasonic_Trigger(void)
{
	/* Give 10us trigger pulse on trig. pin to HC-SR04 */
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU.
 * 3. Return the measured distance in Centimeters.
 */
uint16 Ultrasonic_readDistance(void)
{
	/* Initialize the ULTRASONIC */
	Ultrasonic_init();
	/* Send the Trigger pulse to the ULTRASONIC */
	Ultrasonic_Trigger();
	/* Get the measured distance in Centimeters rounded to the nearest integer value */
	uint16 distance =round((double)(g_timeHigh)/CALIBRATION_FACTOR) ;
	return distance;
}

/*
 * Description :
 * 1. The call back function called by the ICU driver.
 * 2. calculate the high time (pulse time) generated by the ULTRASONIC sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;
	}
}

